ARG ALPINE_VERSION=3.16
ARG GROUP='strange'
ARG USERNAME='youdontneedtoknow'
ARG PORT='8080'
ARG WD='/var/www/html'
#ENV GROUP /'STRANGE'
#ENV USERNAME /'youdontneedtoknow'
FROM alpine:${ALPINE_VERSION}
WORKDIR ${WD}
USER root
RUN apk add --no-cache \
  curl \
  nginx \
  php81 \
  php81-ctype \
  php81-curl \
  php81-dom \
  php81-fpm \
  php81-gd \
  php81-intl \
  php81-mbstring \
  php81-mysqli \
  php81-opcache \
  php81-openssl \
  php81-phar \
  php81-session \
  php81-xml \
  php81-xmlreader \
  supervisor

#RUN ["ln", "-s", "/usr/bin/php81", "/usr/bin/php"]
COPY bin/build/nginx.conf /etc/nginx/nginx.conf
COPY bin/build/fpm-pool.conf /etc/php81/php-fpm.d/www.conf
COPY bin/build/php.ini /etc/php81/conf.d/custom.ini
COPY bin/build/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY --from=composer /usr/bin/composer /usr/bin/composer
RUN chown -R nobody.nobody ${WD} /run /var/lib/nginx /var/log/nginx
USER nobody
COPY --chown=nobody src/ ${WD}/
#RUN composer install --optimize-autoloader --no-interaction --no-progress
EXPOSE ${PORT}
HEALTHCHECK --timeout=15s CMD curl --silent --fail http://127.0.0.1:${PORT}/fpm-ping
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
