controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

homepage:
    path: /
    defaults:
        _controller: App\Controller\DefaultController::indexAction
        tag: false
